# Default configuration for Research Paper Tagger
# You can customize categories and their keywords here

# Processing settings
processing:
  confidence_threshold: 0.3  # Minimum confidence for tag assignment (0.0 - 1.0)
  max_tags: 5               # Maximum number of tags per paper
  extraction_method: "auto" # PDF extraction method: "auto", "pymupdf", "pdfplumber", "pypdf2"

# Output settings
output:
  default_format: "csv"     # Default output format: "csv", "json"
  create_summary: true      # Create tag summary report
  organize_by_tags: false   # Organize files into tag-based directories
  rename_with_tags: false   # Rename files to include tags
  max_filename_tags: 2      # Maximum tags in filename

# Custom categories (add your own here)
categories:
  # Example custom categories
  "Quantum Computing":
    - "quantum computing"
    - "quantum algorithm"
    - "quantum machine learning"
    - "quantum neural network"
    - "quantum circuit"
    - "quantum entanglement"
    - "quantum supremacy"
    - "qubit"
    - "quantum gate"
    - "quantum annealing"
    - "quantum cryptography"
    - "quantum error correction"
    - "quantum simulation"
    - "adiabatic quantum"
    - "variational quantum"
  
  "Blockchain and Cryptocurrency":
    - "blockchain"
    - "cryptocurrency"
    - "bitcoin"
    - "ethereum"
    - "smart contract"
    - "distributed ledger"
    - "consensus mechanism"
    - "proof of work"
    - "proof of stake"
    - "hash function"
    - "merkle tree"
    - "decentralized"
    - "cryptographic hash"
    - "mining"
    - "wallet"
  
  "Explainable AI":
    - "explainable ai"
    - "interpretable machine learning"
    - "model interpretability"
    - "feature importance"
    - "attention visualization"
    - "grad-cam"
    - "lime"
    - "shap"
    - "saliency map"
    - "model explanation"
    - "transparent ai"
    - "black box"
    - "white box"
    - "post-hoc explanation"
    - "intrinsic interpretability"
  
  "Edge Computing":
    - "edge computing"
    - "mobile edge computing"
    - "fog computing"
    - "edge ai"
    - "edge inference"
    - "iot"
    - "internet of things"
    - "edge device"
    - "latency optimization"
    - "bandwidth optimization"
    - "distributed computing"
    - "mobile computing"
    - "ubiquitous computing"
    - "pervasive computing"
    - "embedded system"

# Advanced settings
advanced:
  # Text preprocessing
  remove_stopwords: true
  use_lemmatization: true
  min_word_length: 3
  
  # Classification
  use_tfidf: true
  tfidf_max_features: 10000
  tfidf_ngram_range: [1, 3]
  tfidf_min_df: 2
  tfidf_max_df: 0.95
  
  # Similarity weights
  tfidf_weight: 0.7         # Weight for TF-IDF similarity
  keyword_weight: 0.3       # Weight for keyword matching
  
  # Model persistence
  save_model: false         # Save trained model to disk
  model_path: "models/classifier.pkl"
